### ISSUE TITLE
[Bug] Multidimensional data prediction with MultiTaskGP model

### ISSUE THREAD

**Issue by zhaojingyao** [pytorch/botorch#497]
# 🐛 Bug
When I run the following code, the predicted mean for all tasks look the same.
like: tensor([[0.2293, 0.2293],
        [0.4838, 0.4838]])
When I increase the number of training points, the result is still the same.

def f1(X):
    return torch.sin(pi*X[:,0]) + torch.sin(pi*X[:,1])
    
def f2(X):
    return torch.sin(pi*X[:,0]) - torch.sin(pi*X[:,1])
    
X1, X2 = torch.rand(10, 2), torch.rand(10, 2)
i1, i2 = torch.zeros(10, 1), torch.ones(10, 1)
train_X = torch.cat([torch.cat([X1, i1], -1), torch.cat([X2, i2], -1),])
train_Y = torch.cat([f1(X1), f2(X2)]).unsqueeze(-1)
model = MultiTaskGP(train_X, train_Y, task_feature=-1)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll)
posterior = model.posterior(train_X[:2,:-1])
mean = posterior.mean.cpu().detach()

**Comment by Balandat** [comment]
Can you try this on master? This should have been fixed in #485. (Also you want to make sure that `X` (instead of `piX`) in the function def is actually used).

**Comment by Balandat** [comment]
going to close this for now, feel free to re-open if you can still repro this issue on master.

**Comment by zhaojingyao** [comment]
Thank you for your replay. I download the latest gpytorch-master and /pytorch/botorch-master to my WIN10, and install them with command ‘python setup.py install’. Then I run mycode_mt.py, the predicted outputs of two tasks are still the same.

Could you please try my code and give me some advice? Maybe something is wrong with my code.

发送自 Windows 10 版邮件应用

发件人: Max Balandat
发送时间: 2020年7月31日 9:39
收件人: pytorch/botorch
抄送: zhaojingyao; Author
主题: Re: [pytorch/botorch] [Bug] Multidimensional data prediction withMultiTaskGP model (#497)

going to close this for now, feel free to re-open if you can still repro this issue on master.

**Comment by zhaojingyao** [comment]
[mycode_mt.txt](https://github.com/pytorch/botorch/files/5004987/mycode_mt.txt)

**Comment by zhaojingyao** [comment]
outputs like:

tensor([[1.2071, 1.2071],
        [0.6733, 0.6733],
        [0.9781, 0.9781],
        [0.7799, 0.7799]])
tensor([[0.8652],
        [0.3550],
        [0.9410],
        [1.2619]])
tensor([[-0.7718],
        [-0.1768],
        [ 0.4107],
        [-0.0654]])

**Comment by Balandat** [comment]
Are you sure you installed the package properly / running in the environment that you installed it in?

The output I get from running your script verbatim is the following:

```
tensor([[ 1.3126,  0.1822],
        [ 1.0434, -0.5043],
        [ 0.6240,  0.3345],
        [ 1.6634,  0.0052]])
tensor([[1.3120],
        [1.0433],
        [0.6242],
        [1.6624]])
tensor([[ 0.1814],
        [-0.5032],
        [ 0.3340],
        [ 0.0055]])
```

**Comment by zhaojingyao** [comment]
I‘m sorry. I uninstalled the default version from  'pip Install botorch', downloaded the latest version and installed it manually, and it works fine now.

Another problem is when I use optimize_acqf to optimize ‘qEI’, the following error may occur during the optimization process:


Is there any way to avoid this exception?

Here is my code:

       weights = torch.tensor([0.0]*self.n_tasks)  # the weight defines a particular scalarization / direction 
        weights[t] = 1.0
        best_f_scalar = torch.dot(weights, self.tao)
        objective = LinearMCObjective(weights=weights) 
        sampler = SobolQMCNormalSampler(300)
        qEI = qExpectedImprovement(self.model, best_f=best_f_scalar, sampler=sampler,objective=objective)
        
        new_point, new_EI = optimize_acqf(
            acq_function=qEI,
            bounds=self.bound,
            q=1,
            num_restarts=self.restarts,
            raw_samples=100,
            options={},
        )

发送自 Windows 10 版邮件应用

发件人: Max Balandat
发送时间: 2020年7月31日 21:42
收件人: pytorch/botorch
抄送: zhaojingyao; Author
主题: Re: [pytorch/botorch] [Bug] Multidimensional data prediction withMultiTaskGP model (#497)

Are you sure you installed the package properly / running in the environment that you installed it in?
The output I get from running your script verbatim is the following:
tensor([[ 1.3126,  0.1822],
        [ 1.0434, -0.5043],
        [ 0.6240,  0.3345],
        [ 1.6634,  0.0052]])
tensor([[1.3120],
        [1.0433],
        [0.6242],
        [1.6624]])
tensor([[ 0.1814],
        [-0.5032],
        [ 0.3340],
        [ 0.0055]])

**Comment by Balandat** [comment]
I think you're missing the error?

**Comment by zhaojingyao** [comment]
sorry......

`File "mtbo4.py", line 232, in <module>
    new_x, new_EI = update_av(model)
  File "mtbo4.py", line 214, in update_av
    new_x, new_EI = model.next_x_EI_av()
  File "/home/zjy/Documents/multi-task/test-botorch/circuit/MTBOTorch.py", line 89, in next_x_EI_av
    options={},
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/optim/optimize.py", line 157, in optimize_acqf
    options=options,
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/optim/initializers.py", line 108, in gen_batch_initial_conditions
    X_rnd[start_idx:end_idx].to(device=device)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/utils/transforms.py", line 198, in decorated
    return method(cls, X, **kwargs)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/utils/transforms.py", line 169, in decorated
    return method(cls, X)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/acquisition/monte_carlo.py", line 158, in forward
    posterior = self.model.posterior(X)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/botorch-0.3.0-py3.7.egg/botorch/models/gpytorch.py", line 586, in posterior
    mvn = self(X_full)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/models/exact_gp.py", line 328, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/models/exact_prediction_strategies.py", line 321, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/models/exact_prediction_strategies.py", line 339, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/models/exact_prediction_strategies.py", line 288, in mean_cache
    mean_cache = train_train_covar.inv_matmul(train_labels_offset).squeeze(-1)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/lazy/lazy_tensor.py", line 959, in inv_matmul
    return func.apply(self.representation_tree(), False, right_tensor, *self.representation())
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/functions/_inv_matmul.py", line 47, in forward
    solves = _solve(lazy_tsr, right_tensor)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/functions/_inv_matmul.py", line 11, in _solve
    return lazy_tsr._cholesky()._cholesky_solve(rhs)
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/lazy/lazy_tensor.py", line 415, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat, jitter=settings.cholesky_jitter.value()).contiguous()
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/utils/cholesky.py", line 50, in psd_safe_cholesky
    raise e
  File "/home/zjy/anaconda3/lib/python3.7/site-packages/gpytorch-1.1.1-py3.7.egg/gpytorch/utils/cholesky.py", line 27, in psd_safe_cholesky
    L = torch.cholesky(A, upper=upper, out=out)
RuntimeError: cholesky_cpu: U(159,159) is zero, singular U.`
